#!/bin/bash
# One-liner quick start
# Copy and paste this entire file into your terminal

echo "🤖 Local LLM Chat - One-Liner Quick Start"
echo "========================================="
echo ""
echo "Step 1: Install Python packages"
echo "Run this command:"
echo ""
echo "  pip install llama-cpp-python flask"
echo ""
echo "Step 2: Download a model (pick ONE):"
echo ""
echo "Option A - Orca Mini (FASTEST - Recommended)"
echo "  wget https://huggingface.co/psmathur/orca_mini_v3_gguf/resolve/main/orca-mini-3b.gguf -P models/"
echo ""
echo "Option B - Mistral 7B (BEST QUALITY)"
echo "  wget https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q4_K_M.gguf -P models/"
echo ""
echo "Step 3: Create models directory if needed"
echo "  mkdir -p models"
echo ""
echo "Step 4: Run one of these:"
echo ""
echo "  python3 chat.py              # Simple chat"
echo "  python3 advanced_chat.py     # With tasks"
echo "  python3 web_chat.py          # Web interface at http://localhost:5000"
echo ""
echo "========================================="
echo "That's it! You're ready to chat! 🚀"
