#!/bin/bash
# Quick Access Guide - Run this for options

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  🤖 LOCAL LLM CHAT - QUICK ACCESS                           ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📍 Location: /home/cyberkid/bin/Ai/"
echo ""
echo "🚀 READY TO RUN IMMEDIATELY:"
echo ""
echo "1️⃣  DEMO CHAT (No dependencies needed)"
echo "    Command:"
echo "    cd /home/cyberkid/bin/Ai && ./venv/bin/python3 demo_chat.py"
echo ""
echo "2️⃣  WEB INTERFACE (Beautiful UI)"
echo "    Command:"
echo "    cd /home/cyberkid/bin/Ai && ./venv/bin/python3 web_chat.py"
echo "    Then open: http://localhost:5000"
echo ""
echo "3️⃣  SIMPLE CLI CHAT (Direct terminal)"
echo "    Note: Requires: pip install llama-cpp-python"
echo "    Command:"
echo "    cd /home/cyberkid/bin/Ai && ./venv/bin/python3 chat.py"
echo ""
echo "4️⃣  ADVANCED CLI (With task management)"
echo "    Note: Requires: pip install llama-cpp-python"
echo "    Command:"
echo "    cd /home/cyberkid/bin/Ai && ./venv/bin/python3 advanced_chat.py"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "💾 VIRTUAL ENVIRONMENT MANAGEMENT:"
echo ""
echo "   Activate venv:"
echo "   source /home/cyberkid/bin/Ai/venv/bin/activate"
echo ""
echo "   Install packages:"
echo "   pip install llama-cpp-python"
echo ""
echo "   Deactivate:"
echo "   deactivate"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTATION:"
echo ""
echo "   Quick Start: cat /home/cyberkid/bin/Ai/SETUP_COMPLETE.txt"
echo "   Full Docs:   cat /home/cyberkid/bin/Ai/README.md"
echo "   Overview:    cat /home/cyberkid/bin/Ai/START_HERE.txt"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Everything is ready! Choose an option above and start chatting! 🚀"
echo ""
